# Generated by Django 5.2.8 on 2025-11-07 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado'), ('archivado', 'Archivado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restringido', 'Restringido')], default='publico', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata_adicional', models.JSONField(blank=True, help_text='Metadata adicional en formato JSON', null=True)),
                ('creador', models.ForeignKey(db_column='creador_id', on_delete=django.db.models.deletion.RESTRICT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='catalogacion.categoria')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Categoría de Proyecto',
                'verbose_name_plural': 'Categorías de Proyectos',
                'db_table': 'proyecto_categorias',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', through='proyectos.ProyectoCategoria', to='catalogacion.categoria'),
        ),
        migrations.CreateModel(
            name='ProyectoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, to='catalogacion.etiqueta')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Etiqueta de Proyecto',
                'verbose_name_plural': 'Etiquetas de Proyectos',
                'db_table': 'proyecto_etiquetas',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', through='proyectos.ProyectoEtiqueta', to='catalogacion.etiqueta'),
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, help_text='Color en formato hexadecimal', max_length=7, null=True)),
                ('plantilla_vista', models.CharField(blank=True, max_length=500, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyecto',
                'db_table': 'tipos_proyecto',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['slug'], name='idx_tipos_proyecto_slug'), models.Index(fields=['es_activo'], name='idx_tipos_proyecto_activo')],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(db_column='tipo_proyecto_id', on_delete=django.db.models.deletion.RESTRICT, related_name='proyectos', to='proyectos.tipoproyecto'),
        ),
        migrations.CreateModel(
            name='CampoTipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('etiqueta', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('textarea', 'Área de Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('select', 'Selección Única'), ('multiselect', 'Selección Múltiple'), ('archivo', 'Archivo'), ('url', 'URL'), ('email', 'Email'), ('json', 'JSON')], default='texto', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('es_repetible', models.BooleanField(default=False, help_text='Permite múltiples valores para este campo')),
                ('es_buscable', models.BooleanField(default=True)),
                ('es_indexable', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('valores_posibles', models.JSONField(blank=True, help_text='Opciones para select/multiselect', null=True)),
                ('validador', models.CharField(blank=True, help_text='Regex o validación', max_length=255, null=True)),
                ('valor_por_defecto', models.TextField(blank=True, null=True)),
                ('ayuda', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, help_text='Agrupa campos en secciones', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_proyecto', models.ForeignKey(db_column='tipo_proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='proyectos.tipoproyecto')),
            ],
            options={
                'verbose_name': 'Campo de Tipo de Proyecto',
                'verbose_name_plural': 'Campos de Tipo de Proyecto',
                'db_table': 'campos_tipo_proyecto',
                'ordering': ['tipo_proyecto', 'orden', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_datetime', models.DateTimeField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('valor_archivo', models.CharField(blank=True, max_length=1000, null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para campos repetibles')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('campo_tipo_proyecto', models.ForeignKey(db_column='campo_tipo_proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='proyectos.campotipoproyecto')),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores_campos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Valor de Campo de Proyecto',
                'verbose_name_plural': 'Valores de Campos de Proyecto',
                'db_table': 'valores_campo_proyecto',
                'ordering': ['proyecto', 'campo_tipo_proyecto', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='proyectocategoria',
            index=models.Index(fields=['proyecto'], name='idx_proy_cat_proy'),
        ),
        migrations.AddIndex(
            model_name='proyectocategoria',
            index=models.Index(fields=['categoria'], name='idx_proy_cat_cat'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectocategoria',
            unique_together={('proyecto', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='proyectoetiqueta',
            index=models.Index(fields=['proyecto'], name='idx_proy_etiq_proy'),
        ),
        migrations.AddIndex(
            model_name='proyectoetiqueta',
            index=models.Index(fields=['etiqueta'], name='idx_proy_etiq_etiq'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectoetiqueta',
            unique_together={('proyecto', 'etiqueta')},
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['titulo'], name='idx_proyectos_titulo'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['tipo_proyecto'], name='idx_proyectos_tipo'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['creador'], name='idx_proyectos_creador'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='idx_proyectos_estado'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_publicacion'], name='idx_proyectos_fecha_pub'),
        ),
        migrations.AddIndex(
            model_name='campotipoproyecto',
            index=models.Index(fields=['tipo_proyecto'], name='idx_campos_tipo_proyecto_tipo'),
        ),
        migrations.AddIndex(
            model_name='campotipoproyecto',
            index=models.Index(fields=['orden'], name='idx_campos_tipo_proyecto_orden'),
        ),
        migrations.AlterUniqueTogether(
            name='campotipoproyecto',
            unique_together={('tipo_proyecto', 'slug')},
        ),
        migrations.AddIndex(
            model_name='valorcampoproyecto',
            index=models.Index(fields=['proyecto'], name='idx_valores_campo_proyecto'),
        ),
        migrations.AddIndex(
            model_name='valorcampoproyecto',
            index=models.Index(fields=['campo_tipo_proyecto'], name='idx_valores_campo_campo'),
        ),
        migrations.AddIndex(
            model_name='valorcampoproyecto',
            index=models.Index(fields=['valor_texto'], name='idx_valores_campo_texto'),
        ),
        migrations.AddIndex(
            model_name='valorcampoproyecto',
            index=models.Index(fields=['valor_numero'], name='idx_valores_campo_numero'),
        ),
        migrations.AddIndex(
            model_name='valorcampoproyecto',
            index=models.Index(fields=['valor_fecha'], name='idx_valores_campo_fecha'),
        ),
    ]
