# Generated by Django 5.2.8 on 2025-11-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial_proyectos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del autor', max_length=200)),
                ('apellidos', models.CharField(help_text='Apellidos del autor', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('afiliacion', models.CharField(blank=True, help_text='Institución o afiliación', max_length=500, null=True)),
                ('orcid_id', models.CharField(blank=True, help_text='ID de ORCID', max_length=19, null=True)),
                ('orden_autor', models.PositiveIntegerField(default=1, help_text='Orden de autoría (1 = primer autor)')),
                ('es_correspondiente', models.BooleanField(default=False, help_text='Autor de correspondencia')),
                ('es_autor_principal', models.BooleanField(default=False, help_text='Autor principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario del sistema (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoria_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autor de Proyecto',
                'verbose_name_plural': 'Autores de Proyectos',
                'db_table': 'proyecto_autores',
                'ordering': ['proyecto', 'orden_autor'],
                'indexes': [models.Index(fields=['proyecto'], name='idx_proyecto_autores_proyecto'), models.Index(fields=['usuario'], name='idx_proyecto_autores_usuario'), models.Index(fields=['orden_autor'], name='idx_proyecto_autores_orden'), models.Index(fields=['orcid_id'], name='idx_proyecto_autores_orcid')],
            },
        ),
    ]
