# Generated by Django 5.2.8 on 2025-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20251109_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoautor',
            name='afiliacion',
            field=models.CharField(blank=True, help_text='Institución o afiliación (opcional, si no se proporciona se usa la del usuario)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proyectoautor',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='ID de ORCID (opcional, si no se proporciona se usa la del usuario)', max_length=19, null=True),
        ),
    ]
