# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('numerico', 'Numérico'), ('texto', 'Texto'), ('booleano', 'Booleano'), ('opcion', 'Opción')], default='numerico', max_length=20)),
                ('escala_minima', models.PositiveIntegerField(blank=True, null=True)),
                ('escala_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('opciones', models.JSONField(blank=True, help_text='Opciones para tipo opcion', null=True)),
                ('es_obligatorio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Criterio de Revisión',
                'verbose_name_plural': 'Criterios de Revisión',
                'db_table': 'criterios_revision',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_revision', models.CharField(choices=[('peer_review', 'Peer Review'), ('editorial', 'Editorial'), ('administrativa', 'Administrativa')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_cambios', 'Requiere Cambios')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('notas_generales', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='procesos_revision', to='repositorio.documento')),
                ('iniciado_por', models.ForeignKey(db_column='iniciado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='procesos_revision_iniciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Revisión',
                'verbose_name_plural': 'Procesos de Revisión',
                'db_table': 'procesos_revision',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='asignado', max_length=20)),
                ('calificacion_general', models.PositiveIntegerField(blank=True, help_text='Calificación del 1 al 5', null=True)),
                ('comentarios_publicos', models.TextField(blank=True, null=True)),
                ('comentarios_privados', models.TextField(blank=True, null=True)),
                ('recomendacion', models.CharField(blank=True, choices=[('aprobar', 'Aprobar'), ('aprobar_con_cambios', 'Aprobar con Cambios'), ('rechazar', 'Rechazar'), ('requiere_revision', 'Requiere Revisión')], max_length=30, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True)),
                ('proceso_revision', models.ForeignKey(db_column='proceso_revision_id', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='revisiones.procesorevision')),
                ('revisor', models.ForeignKey(db_column='revisor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='revisiones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'db_table': 'revisiones',
                'ordering': ['proceso_revision', '-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_opcion', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('criterio', models.ForeignKey(db_column='criterio_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='revisiones.criteriorevision')),
                ('revision', models.ForeignKey(db_column='revision_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_criterios', to='revisiones.revision')),
            ],
            options={
                'verbose_name': 'Evaluación de Criterio',
                'verbose_name_plural': 'Evaluaciones de Criterios',
                'db_table': 'evaluaciones_criterios',
            },
        ),
        migrations.AddIndex(
            model_name='procesorevision',
            index=models.Index(fields=['documento'], name='idx_proc_rev_doc'),
        ),
        migrations.AddIndex(
            model_name='procesorevision',
            index=models.Index(fields=['estado'], name='idx_proc_rev_estado'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['proceso_revision'], name='idx_revisiones_proceso'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['revisor'], name='idx_revisiones_revisor'),
        ),
        migrations.AddIndex(
            model_name='evaluacioncriterio',
            index=models.Index(fields=['revision'], name='idx_evaluaciones_revision'),
        ),
        migrations.AddIndex(
            model_name='evaluacioncriterio',
            index=models.Index(fields=['criterio'], name='idx_evaluaciones_criterio'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacioncriterio',
            unique_together={('revision', 'criterio')},
        ),
    ]
