# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plantilla', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificación',
                'db_table': 'tipos_notificacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('mensaje', models.TextField()),
                ('url_relacionada', models.CharField(blank=True, max_length=1000, null=True)),
                ('es_leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, db_column='documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='repositorio.documento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacion', models.ForeignKey(db_column='tipo_notificacion_id', on_delete=django.db.models.deletion.RESTRICT, related_name='notificaciones', to='notificaciones.tiponotificacion')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario'], name='idx_notificaciones_usuario'), models.Index(fields=['tipo_notificacion'], name='idx_notificaciones_tipo'), models.Index(fields=['es_leida'], name='idx_notificaciones_leida'), models.Index(fields=['fecha_creacion'], name='idx_notificaciones_fecha')],
            },
        ),
    ]
