# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaMetadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('prefijo', models.CharField(max_length=50, unique=True)),
                ('namespace', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Esquema de Metadatos',
                'verbose_name_plural': 'Esquemas de Metadatos',
                'db_table': 'esquemas_metadatos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampoMetadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('lista', 'Lista'), ('json', 'JSON')], default='texto', max_length=20)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('es_repetible', models.BooleanField(default=False)),
                ('valores_posibles', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esquema', models.ForeignKey(db_column='esquema_id', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='metadatos.esquemametadatos')),
            ],
            options={
                'verbose_name': 'Campo de Metadatos',
                'verbose_name_plural': 'Campos de Metadatos',
                'db_table': 'campos_metadatos',
                'ordering': ['esquema', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetadatoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_json', models.JSONField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=10, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('campo_metadato', models.ForeignKey(db_column='campo_metadato_id', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='metadatos.campometadatos')),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='metadatos', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Metadato de Documento',
                'verbose_name_plural': 'Metadatos de Documentos',
                'db_table': 'metadatos_documento',
                'ordering': ['documento', 'campo_metadato', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='campometadatos',
            index=models.Index(fields=['esquema'], name='idx_campos_metadatos_esquema'),
        ),
        migrations.AlterUniqueTogether(
            name='campometadatos',
            unique_together={('esquema', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='metadatodocumento',
            index=models.Index(fields=['documento'], name='idx_metadatos_documento'),
        ),
        migrations.AddIndex(
            model_name='metadatodocumento',
            index=models.Index(fields=['campo_metadato'], name='idx_metadatos_campo'),
        ),
        migrations.AddIndex(
            model_name='metadatodocumento',
            index=models.Index(fields=['valor_texto'], name='idx_metadatos_valor_texto'),
        ),
    ]
