# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de Documento',
                'verbose_name_plural': 'Estados de Documento',
                'db_table': 'estados_documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recurso',
                'db_table': 'tipos_recurso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', models.CharField(blank=True, max_length=500, null=True)),
                ('es_publica', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('archivada', 'Archivada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(db_column='administrador_id', on_delete=django.db.models.deletion.RESTRICT, related_name='comunidades_administradas', to=settings.AUTH_USER_MODEL)),
                ('comunidad_padre', models.ForeignKey(blank=True, db_column='comunidad_padre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcomunidades', to='repositorio.comunidad')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'comunidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('politica_ingreso', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('revision', 'Requiere Revisión')], default='abierto', max_length=20)),
                ('es_publica', models.BooleanField(default=True)),
                ('plantilla_metadatos', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(db_column='administrador_id', on_delete=django.db.models.deletion.RESTRICT, related_name='colecciones_administradas', to=settings.AUTH_USER_MODEL)),
                ('coleccion_padre', models.ForeignKey(blank=True, db_column='coleccion_padre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcolecciones', to='repositorio.coleccion')),
                ('comunidad', models.ForeignKey(db_column='comunidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to='repositorio.comunidad')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'db_table': 'colecciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Identificador único permanente', max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion_disponible', models.DateTimeField(blank=True, null=True)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restringido', 'Restringido')], default='publico', max_length=20)),
                ('version_actual', models.PositiveIntegerField(default=1)),
                ('numero_acceso', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('palabras_clave', models.TextField(blank=True, null=True)),
                ('temas', models.JSONField(blank=True, null=True)),
                ('campos_personalizados', models.JSONField(blank=True, null=True)),
                ('metadata_completa', models.JSONField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='documentos', through='catalogacion.DocumentoCategoria', to='catalogacion.categoria')),
                ('coleccion', models.ForeignKey(db_column='coleccion_id', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.coleccion')),
                ('creador', models.ForeignKey(db_column='creador_id', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='documentos', through='catalogacion.DocumentoEtiqueta', to='catalogacion.etiqueta')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.estadodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DerechoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_derecho', models.CharField(choices=[('copyright', 'Copyright'), ('patente', 'Patente'), ('marca', 'Marca'), ('privacidad', 'Privacidad'), ('otros', 'Otros')], max_length=20)),
                ('titular', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='derechos', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Derecho de Documento',
                'verbose_name_plural': 'Derechos de Documentos',
                'db_table': 'derechos_documento',
                'ordering': ['documento', 'tipo_derecho'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('editor', 'Editor'), ('revisor', 'Revisor'), ('colaborador', 'Colaborador'), ('supervisor', 'Supervisor'), ('patrocinador', 'Patrocinador')], max_length=20)),
                ('permisos', models.JSONField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones_documentos', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'colaboradores',
                'ordering': ['documento', 'rol'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('afiliacion', models.CharField(blank=True, max_length=500, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=19, null=True)),
                ('orden_autor', models.PositiveIntegerField(default=1)),
                ('es_correspondiente', models.BooleanField(default=False)),
                ('es_autor_principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoria_documentos', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autores',
                'ordering': ['documento', 'orden_autor'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('repositorio', 'Repositorio'), ('preprint', 'Preprint'), ('version_publisher', 'Versión Publisher'), ('datos', 'Datos'), ('codigo', 'Código'), ('multimedia', 'Multimedia'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_externos', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Enlace Externo',
                'verbose_name_plural': 'Enlaces Externos',
                'db_table': 'enlaces_externos',
                'ordering': ['documento', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('permite_comercial', models.BooleanField(default=False)),
                ('permite_modificacion', models.BooleanField(default=False)),
                ('requiere_attribucion', models.BooleanField(default=True)),
                ('texto_completo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'db_table': 'licencias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='idx_licencias_codigo')],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='licencia',
            field=models.ForeignKey(blank=True, db_column='licencia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='repositorio.licencia'),
        ),
        migrations.CreateModel(
            name='RelacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('version_anterior', 'Versión Anterior'), ('version_posterior', 'Versión Posterior'), ('parte_de', 'Parte De'), ('contiene', 'Contiene'), ('relacionado', 'Relacionado'), ('suplementa', 'Suplementa'), ('cita', 'Cita')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento_destino', models.ForeignKey(db_column='documento_destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_entrantes', to='repositorio.documento')),
                ('documento_origen', models.ForeignKey(db_column='documento_origen_id', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salientes', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Relación de Documento',
                'verbose_name_plural': 'Relaciones de Documentos',
                'db_table': 'relaciones_documentos',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_recurso',
            field=models.ForeignKey(db_column='tipo_recurso_id', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.tiporecurso'),
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('notas_version', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_version_actual', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(db_column='creado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='versiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documento',
                'db_table': 'versiones_documento',
                'ordering': ['documento', '-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=500)),
                ('nombre_almacenado', models.CharField(max_length=500)),
                ('ruta_completa', models.CharField(max_length=1000)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('tamaño_bytes', models.BigIntegerField()),
                ('checksum_md5', models.CharField(blank=True, max_length=32, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_archivo_principal', models.BooleanField(default=False)),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='En segundos', null=True)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(db_column='version_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='repositorio.versiondocumento')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivos',
                'ordering': ['version', '-es_archivo_principal', 'fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['slug'], name='idx_comunidades_slug'),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['comunidad_padre'], name='idx_comunidad_padre'),
        ),
        migrations.AddIndex(
            model_name='comunidad',
            index=models.Index(fields=['administrador'], name='idx_administrador'),
        ),
        migrations.AddIndex(
            model_name='coleccion',
            index=models.Index(fields=['comunidad'], name='idx_colecciones_comunidad'),
        ),
        migrations.AddIndex(
            model_name='coleccion',
            index=models.Index(fields=['coleccion_padre'], name='idx_colecciones_padre'),
        ),
        migrations.AddIndex(
            model_name='coleccion',
            index=models.Index(fields=['administrador'], name='idx_colecciones_admin'),
        ),
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together={('slug', 'comunidad')},
        ),
        migrations.AddIndex(
            model_name='derechodocumento',
            index=models.Index(fields=['documento'], name='idx_derechos_documento'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['documento'], name='idx_colaboradores_documento'),
        ),
        migrations.AddIndex(
            model_name='colaborador',
            index=models.Index(fields=['usuario'], name='idx_colaboradores_usuario'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['documento'], name='idx_autores_documento'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['usuario'], name='idx_autores_usuario'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['orden_autor'], name='idx_autores_orden'),
        ),
        migrations.AddIndex(
            model_name='enlaceexterno',
            index=models.Index(fields=['documento'], name='idx_enlaces_ext_documento'),
        ),
        migrations.AddIndex(
            model_name='relaciondocumento',
            index=models.Index(fields=['documento_origen'], name='idx_relaciones_origen'),
        ),
        migrations.AddIndex(
            model_name='relaciondocumento',
            index=models.Index(fields=['documento_destino'], name='idx_relaciones_destino'),
        ),
        migrations.AlterUniqueTogether(
            name='relaciondocumento',
            unique_together={('documento_origen', 'documento_destino', 'tipo_relacion')},
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['handle'], name='idx_documentos_handle'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['titulo'], name='idx_documentos_titulo'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo_recurso'], name='idx_documentos_tipo_recurso'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['coleccion'], name='idx_documentos_coleccion'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['creador'], name='idx_documentos_creador'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='idx_documentos_estado'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['doi'], name='idx_documentos_doi'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_publicacion'], name='idx_documentos_fecha_pub'),
        ),
        migrations.AddIndex(
            model_name='versiondocumento',
            index=models.Index(fields=['documento'], name='idx_versiones_doc_documento'),
        ),
        migrations.AddIndex(
            model_name='versiondocumento',
            index=models.Index(fields=['creado_por'], name='idx_versiones_doc_creado_por'),
        ),
        migrations.AlterUniqueTogether(
            name='versiondocumento',
            unique_together={('documento', 'numero_version')},
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['version'], name='idx_archivos_version'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['checksum_md5'], name='idx_archivos_checksum'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['tipo_mime'], name='idx_archivos_tipo_mime'),
        ),
    ]
