# Generated by Django 5.2.8 on 2025-11-09 15:43

import django.db.models.deletion
import repositorio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectoautor'),
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF del documento', max_length=1000, null=True, upload_to=repositorio.models.archivo_upload_path),
        ),
        migrations.AddField(
            model_name='documento',
            name='proyecto',
            field=models.OneToOneField(blank=True, db_column='proyecto_id', help_text='Proyecto asociado a este documento. El título y descripción vienen del proyecto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='es_archivo_principal',
            field=models.BooleanField(default=False, help_text='Indica si es el archivo principal (PDF) del documento'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='formato',
            field=models.CharField(blank=True, help_text='Formato del archivo (pdf, doc, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre_almacenado',
            field=models.CharField(blank=True, help_text='Nombre con el que se almacenó (deprecated, usar archivo)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre_original',
            field=models.CharField(help_text='Nombre original del archivo subido', max_length=500),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='numero_paginas',
            field=models.PositiveIntegerField(blank=True, help_text='Número de páginas (para PDFs)', null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='ruta_completa',
            field=models.CharField(blank=True, help_text='Ruta completa (deprecated, usar archivo)', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tamaño_bytes',
            field=models.BigIntegerField(blank=True, help_text='Tamaño en bytes', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='coleccion',
            field=models.ForeignKey(blank=True, db_column='coleccion_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.coleccion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.estadodocumento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='handle',
            field=models.CharField(blank=True, help_text='Identificador único permanente (se genera automáticamente si no se proporciona)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen opcional. Si hay proyecto asociado, se usa el resumen del proyecto.', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_recurso',
            field=models.ForeignKey(blank=True, db_column='tipo_recurso_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='repositorio.tiporecurso'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título opcional. Si hay proyecto asociado, se usa el título del proyecto.', max_length=500, null=True),
        ),
    ]
