# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(db_column='archivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='repositorio.archivo')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargas_archivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de Archivo',
                'verbose_name_plural': 'Descargas de Archivos',
                'db_table': 'descargas_archivo',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['archivo'], name='idx_descargas_archivo'), models.Index(fields=['usuario'], name='idx_descargas_usuario'), models.Index(fields=['fecha'], name='idx_descargas_fecha')],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaAgregada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('total_visitas', models.PositiveIntegerField(default=0)),
                ('total_descargas', models.PositiveIntegerField(default=0)),
                ('visitas_unicas', models.PositiveIntegerField(default=0)),
                ('descargas_unicas', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_lectura', models.PositiveIntegerField(blank=True, help_text='En segundos', null=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_agregadas', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Estadística Agregada',
                'verbose_name_plural': 'Estadísticas Agregadas',
                'db_table': 'estadisticas_agregadas',
                'ordering': ['documento', '-fecha_inicio'],
                'indexes': [models.Index(fields=['documento'], name='idx_estad_agr_doc'), models.Index(fields=['fecha_inicio'], name='idx_estad_agr_fecha')],
                'unique_together': {('documento', 'periodo', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='VisitaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('pais', models.CharField(blank=True, max_length=2, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('referer', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo_acceso', models.CharField(choices=[('vista', 'Vista'), ('descarga', 'Descarga'), ('preview', 'Preview')], default='vista', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='repositorio.documento')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de Documento',
                'verbose_name_plural': 'Visitas de Documentos',
                'db_table': 'visitas_documento',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['documento'], name='idx_visitas_documento'), models.Index(fields=['usuario'], name='idx_visitas_usuario'), models.Index(fields=['fecha'], name='idx_visitas_fecha'), models.Index(fields=['tipo_acceso'], name='idx_visitas_tipo_acceso')],
            },
        ),
    ]
