# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.TextField(blank=True, null=True)),
                ('fecha_citacion', models.DateTimeField(auto_now_add=True)),
                ('documento_citado', models.ForeignKey(db_column='documento_citado_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_recibidas', to='repositorio.documento')),
                ('documento_que_cita', models.ForeignKey(db_column='documento_que_cita_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas_realizadas', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['documento_citado', '-fecha_citacion'],
                'indexes': [models.Index(fields=['documento_citado'], name='idx_citado'), models.Index(fields=['documento_que_cita'], name='idx_que_cita')],
                'unique_together': {('documento_citado', 'documento_que_cita')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_moderado', models.BooleanField(default=False)),
                ('es_publico', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentario_padre', models.ForeignKey(blank=True, db_column='comentario_padre_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='interaccion.comentario')),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='repositorio.documento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
                'ordering': ['documento', '-fecha_creacion'],
                'indexes': [models.Index(fields=['documento'], name='idx_comentarios_documento'), models.Index(fields=['usuario'], name='idx_comentarios_usuario'), models.Index(fields=['comentario_padre'], name='idx_comentarios_padre')],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('articulo', 'Artículo'), ('libro', 'Libro'), ('capitulo', 'Capítulo'), ('tesis', 'Tesis'), ('congreso', 'Congreso'), ('patente', 'Patente'), ('web', 'Web'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('titulo', models.CharField(max_length=500)),
                ('autores', models.TextField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cita_completa', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='referencias_bibliograficas', to='repositorio.documento')),
            ],
            options={
                'verbose_name': 'Referencia Bibliográfica',
                'verbose_name_plural': 'Referencias Bibliográficas',
                'db_table': 'referencias_bibliograficas',
                'ordering': ['documento', 'orden'],
                'indexes': [models.Index(fields=['documento'], name='idx_referencias_documento')],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(help_text='Calificación del 1 al 5')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='repositorio.documento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'valoraciones',
                'ordering': ['documento', '-fecha'],
                'indexes': [models.Index(fields=['documento'], name='idx_valoraciones_documento'), models.Index(fields=['usuario'], name='idx_valoraciones_usuario')],
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
