# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, unique=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano'), ('json', 'JSON'), ('fecha', 'Fecha')], default='texto', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_editable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'ordering': ['categoria', 'clave'],
                'indexes': [models.Index(fields=['clave'], name='idx_config_clave'), models.Index(fields=['categoria'], name='idx_config_categoria')],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'db_table': 'logs_sistema',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['nivel'], name='idx_logs_nivel'), models.Index(fields=['modulo'], name='idx_logs_modulo'), models.Index(fields=['usuario'], name='idx_logs_usuario'), models.Index(fields=['fecha'], name='idx_logs_fecha')],
            },
        ),
    ]
