# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_indexado', models.TextField()),
                ('palabras_clave_indexadas', models.TextField(blank=True, null=True)),
                ('fecha_indexacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Índice de Búsqueda',
                'verbose_name_plural': 'Índices de Búsqueda',
                'db_table': 'indices_busqueda',
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=500)),
                ('filtros_aplicados', models.JSONField(blank=True, null=True)),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'db_table': 'busquedas',
                'ordering': ['-fecha'],
            },
        ),
    ]
