# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busqueda', '0001_initial'),
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicebusqueda',
            name='documento',
            field=models.OneToOneField(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='indice_busqueda', to='repositorio.documento'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['usuario'], name='idx_busquedas_usuario'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['fecha'], name='idx_busquedas_fecha'),
        ),
    ]
