# Generated by Django 5.2.8 on 2025-11-07 03:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('institucion', models.CharField(blank=True, help_text='Institución a la que pertenece', max_length=255, null=True, verbose_name='Institución')),
                ('departamento', models.CharField(blank=True, help_text='Departamento o unidad académica', max_length=255, null=True, verbose_name='Departamento')),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición actual', max_length=100, null=True, verbose_name='Cargo')),
                ('biografia', models.TextField(blank=True, help_text='Biografía o descripción del perfil', null=True, verbose_name='Biografía')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('orcid_id', models.CharField(blank=True, help_text='Identificador ORCID (formato: 0000-0000-0000-0000)', max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El ORCID debe estar en formato: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')], verbose_name='ORCID ID')),
                ('google_scholar_id', models.CharField(blank=True, help_text='ID de Google Scholar', max_length=100, null=True, verbose_name='Google Scholar ID')),
                ('researchgate_id', models.CharField(blank=True, help_text='ID de ResearchGate', max_length=100, null=True, verbose_name='ResearchGate ID')),
                ('linkedin_url', models.URLField(blank=True, help_text='URL del perfil de LinkedIn', max_length=500, null=True, verbose_name='LinkedIn URL')),
                ('email_verificado', models.BooleanField(default=False, help_text='Indica si el email ha sido verificado', verbose_name='Email Verificado')),
                ('ultimo_acceso', models.DateTimeField(blank=True, help_text='Fecha y hora del último acceso al sistema', null=True, verbose_name='Último Acceso')),
                ('preferencias_notificaciones', models.JSONField(blank=True, default=dict, help_text='Preferencias de notificaciones en formato JSON', verbose_name='Preferencias de Notificaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(help_text='Usuario de Django asociado a esta persona', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['orcid_id'], name='idx_persona_orcid'), models.Index(fields=['institucion'], name='idx_persona_institucion'), models.Index(fields=['user'], name='idx_persona_user')],
            },
        ),
    ]
