# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_publicacion', models.CharField(choices=[('revista', 'Revista'), ('libro', 'Libro'), ('congreso', 'Congreso'), ('repositorio', 'Repositorio'), ('otro', 'Otro')], default='repositorio', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url_externa', models.URLField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='publicaciones', through='catalogacion.PublicacionCategoria', to='catalogacion.categoria')),
                ('editor', models.ForeignKey(db_column='editor_id', help_text='Usuario que gestiona la publicación', on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones_editadas', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='publicaciones', through='catalogacion.PublicacionEtiqueta', to='catalogacion.etiqueta')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'publicaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['slug'], name='idx_publicaciones_slug'), models.Index(fields=['editor'], name='idx_publicaciones_editor'), models.Index(fields=['estado'], name='idx_publicaciones_estado'), models.Index(fields=['doi'], name='idx_publicaciones_doi')],
            },
        ),
    ]
