# Generated by Django 5.2.8 on 2025-11-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial_proyectos'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('rol_en_publicacion', models.CharField(blank=True, help_text='artículo principal, capítulo, etc.', max_length=100, null=True)),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(db_column='proyecto_id', on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_relacionadas', to='proyectos.proyecto')),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_relacionados', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name': 'Proyecto de Publicación',
                'verbose_name_plural': 'Proyectos de Publicaciones',
                'db_table': 'publicacion_proyectos',
                'ordering': ['publicacion', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='publicaciones', through='publicaciones.PublicacionProyecto', to='proyectos.proyecto'),
        ),
        migrations.AddIndex(
            model_name='publicacionproyecto',
            index=models.Index(fields=['publicacion'], name='idx_pub_proyecto_publicacion'),
        ),
        migrations.AddIndex(
            model_name='publicacionproyecto',
            index=models.Index(fields=['proyecto'], name='idx_pub_proyecto_proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='publicacionproyecto',
            unique_together={('publicacion', 'proyecto')},
        ),
    ]
