# Generated by Django 5.2.8 on 2025-11-09 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_initial'),
        ('proyectos', '0002_proyectoautor'),
        ('publicaciones', '0002_publicacionproyecto_publicacion_proyectos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='visibilidad',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restringido', 'Restringido')], default='publico', help_text='Controla si la publicación es visible para el público general', max_length=20),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['visibilidad'], name='idx_publicaciones_visibilidad'),
        ),
    ]
