# Generated by Django 5.2.8 on 2025-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_visibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
