# Generated by Django 5.2.8 on 2025-11-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
        ('publicaciones', '0001_initial'),
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocategoria',
            name='documento',
            field=models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, to='repositorio.documento'),
        ),
        migrations.AddField(
            model_name='documentoetiqueta',
            name='documento',
            field=models.ForeignKey(db_column='documento_id', on_delete=django.db.models.deletion.CASCADE, to='repositorio.documento'),
        ),
        migrations.AddIndex(
            model_name='etiqueta',
            index=models.Index(fields=['slug'], name='idx_etiqueta_slug'),
        ),
        migrations.AddField(
            model_name='documentoetiqueta',
            name='etiqueta',
            field=models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, to='catalogacion.etiqueta'),
        ),
        migrations.AddField(
            model_name='publicacioncategoria',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='catalogacion.categoria'),
        ),
        migrations.AddField(
            model_name='publicacioncategoria',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacionetiqueta',
            name='etiqueta',
            field=models.ForeignKey(db_column='etiqueta_id', on_delete=django.db.models.deletion.CASCADE, to='catalogacion.etiqueta'),
        ),
        migrations.AddField(
            model_name='publicacionetiqueta',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug'], name='idx_categoria_slug'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria_padre'], name='idx_categoria_padre'),
        ),
        migrations.AddIndex(
            model_name='documentocategoria',
            index=models.Index(fields=['documento'], name='idx_doc_categoria_documento'),
        ),
        migrations.AddIndex(
            model_name='documentocategoria',
            index=models.Index(fields=['categoria'], name='idx_doc_categoria_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='documentocategoria',
            unique_together={('documento', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='documentoetiqueta',
            index=models.Index(fields=['documento'], name='idx_doc_etiqueta_documento'),
        ),
        migrations.AddIndex(
            model_name='documentoetiqueta',
            index=models.Index(fields=['etiqueta'], name='idx_doc_etiqueta_etiqueta'),
        ),
        migrations.AlterUniqueTogether(
            name='documentoetiqueta',
            unique_together={('documento', 'etiqueta')},
        ),
        migrations.AddIndex(
            model_name='publicacioncategoria',
            index=models.Index(fields=['publicacion'], name='idx_pub_categoria_publicacion'),
        ),
        migrations.AddIndex(
            model_name='publicacioncategoria',
            index=models.Index(fields=['categoria'], name='idx_pub_categoria_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='publicacioncategoria',
            unique_together={('publicacion', 'categoria')},
        ),
        migrations.AddIndex(
            model_name='publicacionetiqueta',
            index=models.Index(fields=['publicacion'], name='idx_pub_etiqueta_publicacion'),
        ),
        migrations.AddIndex(
            model_name='publicacionetiqueta',
            index=models.Index(fields=['etiqueta'], name='idx_pub_etiqueta_etiqueta'),
        ),
        migrations.AlterUniqueTogether(
            name='publicacionetiqueta',
            unique_together={('publicacion', 'etiqueta')},
        ),
    ]
